SELECT	SUM(AMORTIZADO) TOTAL_VENTAS,SUM(IMPORTE_CAJA) AS SUMA_TOTAL_SIN_ANULADO,
		
		(SELECT SUM(IMPORTE_CAJA) FROM V_CAJA_KADEX WHERE FECHA_ANULADO!='' AND ID_CAJA='12160009') AS ANULADOS,
		(SELECT COUNT(FECHA_INICIAL) FROM V_CAJA_KADEX WHERE ID_CAJA='12160009')AS TOTAL_DOC_VENTAS,
		(SELECT COUNT(FECHA_ANULADO) FROM V_CAJA_KADEX WHERE ID_CAJA='12160009' AND FECHA_ANULADO != '')AS DOC_ANULADOS,
		(SELECT SUM(IMPORTE_CAJA) FROM V_CAJA_KADEX WHERE ID_CAJA='12160009' AND ID_TIPOMOV = 'IVA')AS INGRESOS_VARIOS,
		(SELECT SUM(IMPORTE_CAJA) FROM V_CAJA_KADEX WHERE ID_CAJA='12160009' AND ID_TIPOMOV = 'EVA')AS EGRESOS_VARIOS,
		(SELECT SUM(IMPORTE_CAJA) FROM V_CAJA_KADEX WHERE ID_CAJA='12160009' AND ID_TIPOMOV = 'EGE')AS EGRESO_GERENCIA,
		(SELECT isnull(SUM(IMPORTE_CAJA),0) FROM V_CAJA_KADEX WHERE ID_CAJA='12160009' AND TP_DESCRIPCION !='EFECTIVO')AS TOTAL_V_OTROS
		 FROM V_CAJA_KADEX WHERE ID_CAJA='12160009'






SELECT * FROM V_CAJA_KADEX WHERE ID_CAJA='12160009'


SELECT	SUM(IMPORTE)  FROM V_CAJA_KADEX WHERE ID_TIPOMOV='IPV',
		SUM(IMPORTE) - (SELECT SUM(IMPORTE) FROM V_CAJA_KADEX WHERE ID_CAJA='12160008' AND FECHA_ANULADO != '') AS TOTAL_MENOS_ANULADO,
		(SELECT COUNT(FECHA_INICIAL) FROM V_CAJA_KADEX WHERE ID_CAJA='12160008')AS TOTAL_DOC_VENTAS,
		(SELECT	TOTAL_ANULADO=SUM(IMPORTE) FROM V_CAJA_KADEX WHERE ID_CAJA='12160008' AND FECHA_ANULADO != '') AS TOTAL_ANULADO,
		C
		(SELECT ISNULL(SUM(IMPORTE),0) FROM V_CAJA_KADEX WHERE  ID_CAJA='12160008' AND TP_DESCRIPCION !='EFECTIVO') AS TV_OTROS,
		(SELECT SUM(IMPORTE) FROM V_CAJA_KADEX WHERE  ID_CAJA='12160008' AND TP_DESCRIPCION ='EFECTIVO') AS TV_EFECTIVO,
		(SELECT SUM(IMPORTE) FROM V_CAJA_KADEX WHERE ID_CAJA='12160008' AND ID_TIPOMOV = 'IVA') AS TOTAL_IVA,
		(SELECT SUM(IMPORTE) FROM V_CAJA_KADEX WHERE ID_CAJA='12160008' AND ID_TIPOMOV = 'EGE') AS TOTAL_EGE,
		(SELECT SUM(IMPORTE) FROM V_CAJA_KADEX WHERE ID_CAJA='12160008' AND ID_TIPOMOV = 'EVA') AS TOTAL_EVA
		

		FROM V_CAJA_KADEX WHERE ID_CAJA='12160008'



		SELECT * FROM CAJA



SELECT SUM(IMPORTE) FROM V_CAJA_KADEX WHERE ID_CAJA='06160064' AND ID_TIPOMOV = 'IVA'



SELECT * FROM [dbo].[V_TABLA_VENTAS]

