SELECT  VT.V_TIPO_DOC,VT.V_NUMERO, ID_COMPVENT,(SELECT COUNT(ID_COMPVENT) FROM V_CAJA_KADEX WHERE ID_CAJA = '12160009' GROUP BY ID_CAJA)
			FROM V_CAJA_KADEX AS VC 
			INNER JOIN V_TABLA_VENTAS AS VT ON  VC.ID_COMPVENT = VT.V_ID_VENTA 
			WHERE ID_CAJA = '12160009  '
            ORDER BY V_NUMERO



SELECT  COUNT(V_NUMERO) FROM V_TABLA_VENTAS AS TV
						 INNER JOIN V_CAJA_KADEX AS CK ON TV.V_ID_VENTA = CK.ID_COMPVENT  
						 WHERE V_TIPO_DOC = 'TB'	AND  ID_CAJA = '01160074'



V_TIPO_DOC,TV.V_NUMERO FROM V_TABLA_VENTAS AS TV
				
				  INNER JOIN V_CAJA_KADEX AS CK ON TV.V_ID_VENTA = CK.ID_COMPVENT 
				  WHERE ID_CAJA = '01160074'
				  ORDER BY V_NUMERO 
				  


SELECT * FROM VENTA WHERE ID_VENTA='11160005'



SELECT * FROM CAJA WHERE ID_CAJA='01160074'


SELECT * FROM V_CAJA_KADEX WHERE ID_CAJA='01160074'